services:
  nix:
    build: ./compose
    # NOTE: /src is for runtime only (not build time, hence ./compose is context for build)
    volumes:
      - ./:/src
    working_dir: /src

# FYI intended use:
#   docker compose run --build --rm nix
